# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4878d63de1c74984c9f35fb9da07b3c7f0a1c1278f889b8ec8a71ea59e3bb0667e6aff85cfe51341f8798b7873ab04455c80e490254b184155fc9647deb1e1ed

test:
  secret_key_base: 520953a2a036e308b5cc03c11a17a189d68242692a767f2c09b0206ee59f97d9411b89b1c0ed8544d6751eb83b1ab8859a60fa72907f00b963b5fb9ec0683aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
