namespace :setup do
  task :init do
    puts ">init: Task to initiate a process"
    puts ">Imagine that all other tasks depend on this task"
  end
             
  task :cleanup => :init do #This task depends on :init
    puts ">>cleanup:Tasks related to cleaning up Gemfile, deleting public/index.html etc."
  end                  
  task :git=> :init do #This one too depends on :init
    puts ">>>git: Tasks concerned with setting up GIT repository"
  end
                               
  task :all => [ :init, :cleanup, :git ] do #Depends on init, cleanup and git tasks.
    puts ">>>>all: Done"
  end
end
